# [dbo].[Sexo]

In [ ]:
USE [WebTeste.Models.UserDbContext]
GO

In [ ]:
/****** Object:  Table [dbo].[Sexo]    Script Date: 04/10/2021 17:00:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sexo](
	[SexoId] [int] NOT NULL,
	[Descricao] [varchar](15) NOT NULL,
 CONSTRAINT [PK_Sexo] PRIMARY KEY CLUSTERED 
(
	[SexoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Usuario]

In [ ]:
/****** Object:  Table [dbo].[Usuario]    Script Date: 04/10/2021 17:00:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[UsuarioId] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](max) NOT NULL,
	[DataNascimento] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Senha] [nvarchar](max) NULL,
	[SexoId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.usuario] PRIMARY KEY CLUSTERED 
(
	[UsuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Sexo]

In [ ]:
INSERT [dbo].[Sexo] ([SexoId], [Descricao]) VALUES (1, N'Feminino')
INSERT [dbo].[Sexo] ([SexoId], [Descricao]) VALUES (2, N'Masculino')
GO

# [dbo].[Usuario]

In [ ]:
SET IDENTITY_INSERT [dbo].[Usuario] ON 
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (9, N'Bilie Joe', N'2008-01-10', N'bilie@gmail.com', N'654', 2)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (13, N'teste de Usuario', N'2015-04-14', N'ads@tes.com', N'123', 1)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (16, N'teste de novo usuario', N'2019-08-11', N'sdfsadf@tres.com', N'321', 1)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (17, N'ZCZD', N'1987-11-05', N'teste@eee.com', N'123', 1)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (18, N'sdsdfsdf', N'1960-11-17', N'slksdf@sldkjf.com', N'23234', 1)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (19, N'poi', N'2001-08-08', N'skfj@lsakdfj.com', N'555', 1)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (20, N'teste ww', N'2011-11-11', N'asdf@asd.com', N'654', 2)
INSERT [dbo].[Usuario] ([UsuarioId], [Nome], [DataNascimento], [Email], [Senha], [SexoId]) VALUES (21, N'456456', N'1956-04-05', N'poi@Poi.com', N'234', 1)
SET IDENTITY_INSERT [dbo].[Usuario] OFF
GO

# [FK__Usuario__SexoId__36B12243]

In [ ]:
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD FOREIGN KEY([SexoId])
REFERENCES [dbo].[Sexo] ([SexoId])
GO